apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: videos-pvc
  namespace: text2video
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: <your-storage-class>
